// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFYqwefJ3PWD0IJUhE_2LxR8CYJN0hwm8',
    appId: '1:533848239474:web:dd3a5a642d76b5dbca01eb',
    messagingSenderId: '533848239474',
    projectId: 'final-project-smart-ac-7b829',
    authDomain: 'final-project-smart-ac-7b829.firebaseapp.com',
    storageBucket: 'final-project-smart-ac-7b829.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE_0i7Blynhp_xPcqkvSFrMmFtk2bAjts',
    appId: '1:533848239474:android:0c76f2ab6e154abdca01eb',
    messagingSenderId: '533848239474',
    projectId: 'final-project-smart-ac-7b829',
    storageBucket: 'final-project-smart-ac-7b829.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFYqwefJ3PWD0IJUhE_2LxR8CYJN0hwm8',
    appId: '1:533848239474:web:f6310c5f60703244ca01eb',
    messagingSenderId: '533848239474',
    projectId: 'final-project-smart-ac-7b829',
    authDomain: 'final-project-smart-ac-7b829.firebaseapp.com',
    storageBucket: 'final-project-smart-ac-7b829.appspot.com',
  );
}
